### ISSUE TITLE
How to run without admin right (OpenShift by default das not allow this)

### ISSUE THREAD

**Issue by dennisseidel** [ot4i/iib-docker#25]
Hi, 

I try to make my image run on OpenShift and they by default prevent you to run you image as root. They basically logon with the -u option as a random user. And this also prevents the use of sudo. 

Is there any option to get the iib logs without   sudo /usr/sbin/rsyslogd. 

Thanks in advance. 

Dennis

PS: There is an option to allows root access in OpenShift, but that would be a last resort.

**Comment by bshaw** [comment]
I'm currently fighting issues related to the security context in OpenShift, too. The inability to use syslog is making it very difficult to troubleshoot!

I was able to solve a couple simple issues by creating the mqbrkrs group with gid 0 (to match the root group, which the container runs as) and opening up the permissions on a few directories so the ghost user has access to them. Now I'm at a point where it fails to create an execution group in the integration node, and due to no syslog, I don't know why.

Interestingly, I've run in docker as a non-root user to simulate the OpenShift security, but it still works there. In this case, we will **not** be allowed to use a privileged container in OpenShift.

I'm happy to provide any logs or try some troubleshooting steps to help work through this.

I should also mention that I'm not using this Dockerfile, rather a custom one I've written based on my company's base RHEL7 image.

**Comment by dennisseidel** [comment]
I worked around it with a ServiceAccount and RunAsAny which allows me to run the container as root. But that won't help in the long run, so I will have investigate this issue further.
