### ISSUE TITLE
toolkit omitted

### ISSUE THREAD

**Issue by CPTFU** [ot4i/iib-docker#49]
> What the image contains (...) full installation of IBM Integration Bus for Developer 

This is misleading since at installation following argument omits the installation of the toolkit:

`--exclude iib-10.0.0.11/tools`

Without the tools we cannot automate **.bar** file building and deploying.

**Comment by dcb-robinson** [comment]
Thanks for the feedback.

Apologies that you found the README misleading, perhaps we should change it to say that the image contains a full installation of the runtime?

We exclude the toolkit from the image as it is not needed to run applications in the container, and it increases the size of the image by a significant amount.

Please note that you are free to build your own image with the toolkit included. I would recommend a read of the following article (if you haven't already):
https://developer.ibm.com/integration/blog/2017/04/04/ibm-integration-bus-docker-tips-tricks/

**Comment by CPTFU** [comment]
This depends highly on the intention of this image.
Since the developer edition is used, imho the toolkit should be included as well to have a full set running.
It would allow for automation processes, where the dev environment can create .bar files to be exported to QA/Test environment.

But changing the README would suffice, since it would also comply with the docker hub description.

Ultimately it is up to you :)

**Comment by bthomps** [comment]
Thanks for the feedback ... Dan, can I suggest we use this issue to update the README to clarify that the Toolkit is excluded please.  

Regarding the intention of the image, we're focussing on this particular example more as a runtime container than for hosting the toolkit / headless mqsicreatebar build command. Of course some users would use the mqsipackagebar command (which doesnt require a Toolkit installation) rather than mqsicreatebar (assuming the artifacts they build are compatible with the more modern "source deploy" alternative).
